services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - C:/Users/PC/Desktop/cours/Projet_DevAppWeb:/usr/share/nginx/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"  # Accédez à phpMyAdmin via http://localhost:8080
    depends_on:
      - db

  sails:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./path/to/sails/app:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
    depends_on:
      - db

volumes:
  db_data:
