services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: league_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  # Backend Sails.js
  sails_api:
    build:
      context: ./api # Chemin du dossier contenant le backend
      dockerfile: Dockerfile
    container_name: sails_api
    ports:
      - "1337:1337"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  # Frontend Vue.js
  vue_client:
    build:
      context: ./client # Chemin du dossier contenant le frontend Vue.js
      dockerfile: Dockerfile
    container_name: vue_client
    ports:
      - "3000:80" # Vue.js sera accessible via le port 3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - sails_api

volumes:
  mysql_data:
